version: '3'

services:
  db:
    image: mariadb:10.11
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MARIADB_DATABASE=wordpress
    volumes:
      - ./db:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  wordpress:
    depends_on:
      - db
    image: wordpress:6.2-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - app-network

  webserver:
    depends_on: 
      - wordpress
    image: nginx:1.25-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
      # - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./nginx/nginx.ssl.conf:/etc/nginx/nginx.conf
      # - ./nginx/options-ssl-nginx.conf:/etc/nginx/options-ssl-nginx.conf
      - ./wordpress:/var/www/html
      - ./certbot-etc:/etc/letsencrypt
    networks:
      - app-network

  certbot:
    depends_on:
      - webserver
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot-etc:/etc/letsencrypt
      - ./wordpress:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email sammy@your_domain --agree-tos --no-eff-email --force-renewal -d your_domain -d www.your_domain

volumes:
  db:
  wordpress:
  certbot-etc:

networks:
  app-network:
    driver: bridge  

